name: spring
description: A simple but powefull animation kit.
version: 0.0.7
author: Kaushick S Argekar
homepage: https://github.com/KaushickSArgekar/spring

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.3.12
  sized_context: ^0.2.1+1
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

